export * from '../icons/Team';
export * from '../icons/Task';
export { default as TaskSvg } from './Task.svg';
export { default as TeamSvg } from './Team.svg';
export { default as analystic } from './analystic.svg';
export { default as dataFolder } from './dataFolder.svg';
export { default as info } from './info.svg';
export { default as interface } from './interface.svg';
export { default as notification } from './notification.svg';
export { default as ranking } from './ranking.svg';
export { default as report } from './report.svg';
export { default as teamWork } from './teamWork.svg';
